#!/usr/bin/env python3
"""Upload/download PolicyWatch generated JSON to Cloudflare R2 (S3-compatible)."""

from __future__ import annotations

import argparse
import mimetypes
import os
import sys
from pathlib import Path
from typing import Iterable, List, Sequence, Tuple

ROOT = Path(__file__).resolve().parents[2]

# Browser-facing files under docs/ (R2 key == path relative to docs/)
DOCS_UPLOAD_FILES = [
    "site_data.json",
    "home_feed.json",
    "legislator_votes.json",
    "legislator_vote_counts.json",
    "bill_title_lookup.json",
    "bill_url_lookup.json",
    "live_status.json",
    "live-streams-config.json",
    "weekly/latest.json",
]

# Pipeline caches that exceed GitHub's 100MB blob limit when committed
PIPELINE_UPLOAD_GLOBS = [
    "data/normalized/*.json",
    "data/openstates/*/bills*.json",
    "data/openstates/*/votes.json",
]


def _require_env(name: str) -> str:
    value = (os.environ.get(name) or "").strip()
    if not value:
        raise SystemExit(f"Missing required env var: {name}")
    return value


def _client():
    try:
        import boto3
        from botocore.config import Config
    except ImportError as exc:
        raise SystemExit(
            "boto3 is required for R2 sync. Install with: pip install boto3"
        ) from exc

    account_id = _require_env("R2_ACCOUNT_ID")
    access_key = _require_env("R2_ACCESS_KEY_ID")
    secret_key = _require_env("R2_SECRET_ACCESS_KEY")
    return boto3.client(
        "s3",
        endpoint_url=f"https://{account_id}.r2.cloudflarestorage.com",
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        region_name="auto",
        config=Config(signature_version="s3v4"),
    )


def _content_type(path: Path) -> str:
    guessed, _ = mimetypes.guess_type(str(path))
    return guessed or "application/octet-stream"


def _collect_docs_files() -> List[Tuple[Path, str]]:
    docs = ROOT / "docs"
    pairs: List[Tuple[Path, str]] = []
    for rel in DOCS_UPLOAD_FILES:
        path = docs / rel
        if path.is_file():
            pairs.append((path, rel.replace("\\", "/")))
        else:
            print(f"skip missing docs file: {rel}")
    # Also upload weekly overview text/audio if present
    weekly = docs / "weekly"
    if weekly.is_dir():
        for path in weekly.iterdir():
            if path.is_file() and path.name != "latest.json":
                pairs.append((path, f"weekly/{path.name}"))
    return pairs


def _collect_pipeline_files() -> List[Tuple[Path, str]]:
    pairs: List[Tuple[Path, str]] = []
    for pattern in PIPELINE_UPLOAD_GLOBS:
        for path in ROOT.glob(pattern):
            if path.is_file():
                rel = path.relative_to(ROOT).as_posix()
                pairs.append((path, rel))
    return pairs


def upload(paths: Sequence[Tuple[Path, str]], *, dry_run: bool = False) -> int:
    bucket = os.environ.get("R2_BUCKET_NAME", "").strip() or "PolicyWatch-data"
    if not dry_run:
        bucket = _require_env("R2_BUCKET_NAME")
    if dry_run:
        for path, key in paths:
            print(f"DRY-RUN upload {path} -> s3://{bucket}/{key} ({path.stat().st_size} bytes)")
        return len(paths)

    client = _client()
    uploaded = 0
    for path, key in paths:
        size = path.stat().st_size
        print(f"upload {key} ({size / (1024 * 1024):.1f} MB)")
        extra = {
            "ContentType": _content_type(path),
            "CacheControl": "public, max-age=60",
        }
        client.upload_file(str(path), bucket, key, ExtraArgs=extra)
        uploaded += 1
    print(f"Uploaded {uploaded} objects to r2://{bucket}")
    return uploaded


def write_data_config() -> Path:
    """Write docs/data-config.js so the site knows where to fetch JSON."""
    base = (os.environ.get("R2_PUBLIC_BASE_URL") or "").strip().rstrip("/")
    out = ROOT / "docs" / "data-config.js"
    contents = (
        "/* Generated by CI — PolicyWatch data base URL (Cloudflare R2). */\n"
        f"window.POLICYWATCH_DATA_BASE = {base!r};\n"
        "window.CIVICWATCH_DATA_BASE = window.POLICYWATCH_DATA_BASE;\n"
    )
    out.write_text(contents, encoding="utf-8")
    print(f"Wrote {out} with base={base or '(empty — same-origin)'}")
    return out


def download_pipeline(*, dry_run: bool = False) -> int:
    """Restore pipeline caches from R2 into the workspace (best-effort)."""
    bucket = _require_env("R2_BUCKET_NAME")
    prefixes = ["data/normalized/", "data/openstates/"]
    if dry_run:
        print(f"DRY-RUN download prefixes {prefixes} from {bucket}")
        return 0

    client = _client()
    downloaded = 0
    for prefix in prefixes:
        token = None
        while True:
            kwargs = {"Bucket": bucket, "Prefix": prefix}
            if token:
                kwargs["ContinuationToken"] = token
            resp = client.list_objects_v2(**kwargs)
            for obj in resp.get("Contents") or []:
                key = obj["Key"]
                dest = ROOT / key
                dest.parent.mkdir(parents=True, exist_ok=True)
                print(f"download {key} -> {dest}")
                client.download_file(bucket, key, str(dest))
                downloaded += 1
            if not resp.get("IsTruncated"):
                break
            token = resp.get("NextContinuationToken")
    print(f"Downloaded {downloaded} pipeline objects from R2")
    return downloaded


def main(argv: Iterable[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    up = sub.add_parser("upload", help="Upload docs + pipeline JSON to R2")
    up.add_argument("--docs-only", action="store_true")
    up.add_argument("--pipeline-only", action="store_true")
    up.add_argument("--dry-run", action="store_true")

    sub.add_parser("write-config", help="Write docs/data-config.js from R2_PUBLIC_BASE_URL")

    down = sub.add_parser("download-pipeline", help="Download pipeline caches from R2")
    down.add_argument("--dry-run", action="store_true")

    args = parser.parse_args(list(argv) if argv is not None else None)

    if args.command == "write-config":
        write_data_config()
        return

    if args.command == "download-pipeline":
        download_pipeline(dry_run=args.dry_run)
        return

    if args.command == "upload":
        pairs: List[Tuple[Path, str]] = []
        if args.pipeline_only:
            pairs.extend(_collect_pipeline_files())
        elif args.docs_only:
            pairs.extend(_collect_docs_files())
        else:
            pairs.extend(_collect_docs_files())
            pairs.extend(_collect_pipeline_files())
        # de-dupe by key
        seen = set()
        unique = []
        for path, key in pairs:
            if key in seen:
                continue
            seen.add(key)
            unique.append((path, key))
        write_data_config()
        upload(unique, dry_run=args.dry_run)
        return

    raise SystemExit(f"Unknown command: {args.command}")


if __name__ == "__main__":
    main()
