#!/usr/bin/env python3
"""Upload/download PolicyWatch generated JSON to Cloudflare R2 (S3-compatible)."""

from __future__ import annotations

import argparse
import json
import mimetypes
import os
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

# Refuse to publish a search archive that is drastically smaller than the
# normalized corpus (guards against rebuilding from stale site_data.json).
HOME_SEARCH_MIN_COVERAGE = 0.90
HOME_SEARCH_MAX_ABS_SHORTFALL = 10_000

# Refuse to publish truncated normalized corpus artifacts when local counts diverge.
NORMALIZED_COUNT_MAX_REL_GAP = 0.10
NORMALIZED_COUNT_MAX_ABS_GAP = 5_000
CRITICAL_NORMALIZED_KEYS = (
    "data/normalized/meta.json",
    "data/normalized/bills.json",
    "data/normalized/search_index.json",
)

# Browser-facing files under docs/ (R2 key == path relative to docs/)
DOCS_UPLOAD_FILES = [
    "site_data.json",
    "home_feed.json",
    "home_search_bills.json",
    "legislators_directory.json",
    "hearings.json",
    "legislator_votes.json",
    "legislator_vote_counts.json",
    "bill_title_lookup.json",
    "bill_url_lookup.json",
    "live_status.json",
    "live-streams-config.json",
    "weekly/latest.json",
]

# On-demand older homepage days (generated by summarize / home_feed.py)
DOCS_UPLOAD_GLOBS = [
    "home_feed_days/*.json",
]

# Pipeline caches that exceed GitHub's 100MB blob limit when committed
PIPELINE_UPLOAD_GLOBS = [
    "data/normalized/*.json",
    "data/openstates/*/bills*.json",
    "data/openstates/*/votes.json",
]


def _require_env(name: str) -> str:
    value = (os.environ.get(name) or "").strip()
    if not value:
        raise SystemExit(f"Missing required env var: {name}")
    return value


def _client():
    try:
        import boto3
        from botocore.config import Config
    except ImportError as exc:
        raise SystemExit(
            "boto3 is required for R2 sync. Install with: pip install boto3"
        ) from exc

    account_id = _require_env("R2_ACCOUNT_ID")
    access_key = _require_env("R2_ACCESS_KEY_ID")
    secret_key = _require_env("R2_SECRET_ACCESS_KEY")
    return boto3.client(
        "s3",
        endpoint_url=f"https://{account_id}.r2.cloudflarestorage.com",
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        region_name="auto",
        config=Config(signature_version="s3v4"),
    )


def _content_type(path: Path) -> str:
    guessed, _ = mimetypes.guess_type(str(path))
    return guessed or "application/octet-stream"


def _collect_docs_files() -> List[Tuple[Path, str]]:
    docs = ROOT / "docs"
    pairs: List[Tuple[Path, str]] = []
    for rel in DOCS_UPLOAD_FILES:
        path = docs / rel
        if path.is_file():
            pairs.append((path, rel.replace("\\", "/")))
        else:
            print(f"skip missing docs file: {rel}")
    for pattern in DOCS_UPLOAD_GLOBS:
        for path in sorted(docs.glob(pattern)):
            if path.is_file():
                rel = path.relative_to(docs).as_posix()
                pairs.append((path, rel))
    # Also upload weekly overview text/audio if present
    weekly = docs / "weekly"
    if weekly.is_dir():
        for path in weekly.iterdir():
            if path.is_file() and path.name != "latest.json":
                pairs.append((path, f"weekly/{path.name}"))
    return pairs


def _collect_pipeline_files() -> List[Tuple[Path, str]]:
    pairs: List[Tuple[Path, str]] = []
    for pattern in PIPELINE_UPLOAD_GLOBS:
        for path in ROOT.glob(pattern):
            if path.is_file():
                rel = path.relative_to(ROOT).as_posix()
                pairs.append((path, rel))
    return pairs


def _meta_bill_count(meta: Any) -> Optional[int]:
    counts = meta.get("counts") if isinstance(meta, dict) else None
    if not isinstance(counts, dict):
        return None
    try:
        value = int(counts.get("bills") or 0)
    except (TypeError, ValueError):
        return None
    return value if value > 0 else None


def _normalized_bill_count() -> Optional[int]:
    meta_path = ROOT / "data" / "normalized" / "meta.json"
    if not meta_path.is_file():
        return None
    try:
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return _meta_bill_count(meta)


def _bill_count(index: Optional[Dict[str, Any]]) -> int:
    bills = (index or {}).get("bills") if isinstance(index, dict) else None
    return len(bills) if isinstance(bills, list) else 0


def _counts_diverge(
    a: int,
    b: int,
    *,
    max_rel: float = NORMALIZED_COUNT_MAX_REL_GAP,
    max_abs: int = NORMALIZED_COUNT_MAX_ABS_GAP,
) -> bool:
    """True when two positive counts diverge by >max_rel or >max_abs."""
    if a < 0 or b < 0:
        return True
    gap = abs(a - b)
    if gap == 0:
        return False
    larger = max(a, b, 1)
    return gap > max_abs or (gap / larger) > max_rel


def _count_bills_in_normalized_file(path: Path, key: str) -> Optional[int]:
    """Return bill count for a critical normalized artifact, or None if unreadable."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"warning: could not read {path}: {exc}")
        return None
    if key.endswith("/meta.json"):
        return _meta_bill_count(data)
    if key.endswith("/bills.json"):
        return len(data) if isinstance(data, list) else None
    if key.endswith("/search_index.json"):
        n = _bill_count(data if isinstance(data, dict) else None)
        return n if n > 0 else None
    return None


def _collect_normalized_bill_counts(
    paths: Optional[Sequence[Tuple[Path, str]]] = None,
) -> Dict[str, int]:
    """Bill counts for critical normalized files that exist locally."""
    by_key = {key: path for path, key in (paths or [])}
    counts: Dict[str, int] = {}
    for key in CRITICAL_NORMALIZED_KEYS:
        path = by_key.get(key) or (ROOT / key)
        if not path.is_file():
            continue
        n = _count_bills_in_normalized_file(path, key)
        if n is not None:
            counts[key] = n
    return counts


def _normalized_consistency_issues(counts: Dict[str, int]) -> List[str]:
    """Return human-readable issues when critical normalized counts diverge hard."""
    items = sorted(counts.items())
    issues: List[str] = []
    for i, (key_a, count_a) in enumerate(items):
        for key_b, count_b in items[i + 1 :]:
            if _counts_diverge(count_a, count_b):
                issues.append(f"{key_a}={count_a} vs {key_b}={count_b}")
    return issues


def prefer_search_index(
    site_search_index: Optional[Dict[str, Any]] = None,
    *,
    normalized_path: Optional[Path] = None,
) -> Dict[str, Any]:
    """Prefer data/normalized/search_index.json when it has more bills than site_data."""
    site_index = site_search_index if isinstance(site_search_index, dict) else {}
    path = normalized_path or (ROOT / "data" / "normalized" / "search_index.json")
    if not path.is_file():
        return site_index
    try:
        normalized = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"warning: could not read {path}: {exc}")
        return site_index
    if not isinstance(normalized, dict):
        return site_index
    site_n = _bill_count(site_index)
    norm_n = _bill_count(normalized)
    if norm_n > site_n:
        print(
            f"Using normalized search_index ({norm_n} bills) over "
            f"site_data.search_index ({site_n} bills)"
        )
        return normalized
    if site_n:
        print(f"Using site_data.search_index ({site_n} bills)")
    return site_index if site_n else normalized


def _legislator_state_coverage(rows: Sequence[Dict[str, Any]]) -> int:
    return len(
        {
            str(row.get("state") or "").strip().upper()
            for row in rows
            if isinstance(row, dict) and str(row.get("state") or "").strip()
        }
        - {"", "FEDERAL"}
    )


def prefer_legislators(
    site_search_index: Optional[Dict[str, Any]] = None,
    *,
    preferred_index: Optional[Dict[str, Any]] = None,
    normalized_legislators_path: Optional[Path] = None,
) -> List[Dict[str, Any]]:
    """Pick the fuller legislator list (prefer normalized coverage over stale indexes)."""
    site_index = site_search_index if isinstance(site_search_index, dict) else {}
    preferred = preferred_index if isinstance(preferred_index, dict) else {}
    site_legs = site_index.get("legislators") or []
    pref_legs = preferred.get("legislators") or []
    if not isinstance(site_legs, list):
        site_legs = []
    if not isinstance(pref_legs, list):
        pref_legs = []

    candidates: List[Tuple[str, List[Dict[str, Any]]]] = []
    if pref_legs:
        candidates.append(("preferred search_index", list(pref_legs)))
    if site_legs:
        candidates.append(("site_data search_index", list(site_legs)))

    norm_path = normalized_legislators_path or (
        ROOT / "data" / "normalized" / "legislators.json"
    )
    if norm_path.is_file():
        try:
            normalized = json.loads(norm_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            print(f"warning: could not read {norm_path}: {exc}")
            normalized = None
        if isinstance(normalized, list) and normalized:
            candidates.append(("normalized legislators.json", list(normalized)))

    if not candidates:
        return []

    def _rank(item: Tuple[str, List[Dict[str, Any]]]) -> Tuple[int, int]:
        rows = item[1]
        return (_legislator_state_coverage(rows), len(rows))

    label, chosen = max(candidates, key=_rank)
    print(
        f"Using {label} ({len(chosen)} legislators, "
        f"{_legislator_state_coverage(chosen)} states)"
    )
    return chosen


def prefer_legislator_stats(
    site_stats: Optional[Dict[str, Any]] = None,
    *,
    normalized_path: Optional[Path] = None,
) -> Dict[str, Any]:
    """Prefer data/normalized/legislator_stats.json when it has more by_state coverage."""
    site = site_stats if isinstance(site_stats, dict) else {}
    path = normalized_path or (ROOT / "data" / "normalized" / "legislator_stats.json")
    if not path.is_file():
        return site
    try:
        normalized = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"warning: could not read {path}: {exc}")
        return site
    if not isinstance(normalized, dict):
        return site
    site_n = len((site.get("by_state") or {})) if isinstance(site.get("by_state"), dict) else 0
    norm_n = (
        len((normalized.get("by_state") or {}))
        if isinstance(normalized.get("by_state"), dict)
        else 0
    )
    if norm_n >= site_n and (norm_n or not site_n):
        if norm_n:
            print(f"Using normalized legislator_stats ({norm_n} states)")
        return normalized
    if site_n:
        print(f"Using site_data legislator_stats ({site_n} states)")
    return site if site_n else normalized


def _validate_docs_upload(paths: Sequence[Tuple[Path, str]]) -> None:
    """Refuse to publish broken home_feed / incomplete home_search archives."""
    by_key = {key: path for path, key in paths}

    home_feed_path = by_key.get("home_feed.json")
    if home_feed_path is not None:
        try:
            data = json.loads(home_feed_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise SystemExit(f"Invalid home_feed.json at {home_feed_path}: {exc}") from exc
        if data.get("home_feed"):
            available = data.get("available_dates") or []
            if not isinstance(available, list) or not available:
                raise SystemExit(
                    "Refusing to upload home_feed.json without available_dates "
                    "(would break homepage Older activity paging). "
                    "Rebuild with: python src/processing/r2_sync.py rebuild-home-feeds"
                )
            print(f"home_feed.json OK ({len(available)} available_dates)")

    search_path = by_key.get("home_search_bills.json")
    if search_path is not None:
        try:
            search_data = json.loads(search_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise SystemExit(f"Invalid home_search_bills.json at {search_path}: {exc}") from exc
        bills = (
            search_data
            if isinstance(search_data, list)
            else (search_data.get("bills") if isinstance(search_data, dict) else None)
        )
        search_n = len(bills) if isinstance(bills, list) else 0
        expected = _normalized_bill_count()
        print(f"home_search_bills.json OK ({search_n} bills)")
        if expected:
            shortfall = expected - search_n
            min_coverage = int(expected * HOME_SEARCH_MIN_COVERAGE)
            if search_n < min_coverage or shortfall > HOME_SEARCH_MAX_ABS_SHORTFALL:
                raise SystemExit(
                    f"Refusing to upload home_search_bills.json with {search_n} bills; "
                    f"normalized corpus has {expected} bills "
                    f"(need >= {HOME_SEARCH_MIN_COVERAGE:.0%} coverage and "
                    f"shortfall <= {HOME_SEARCH_MAX_ABS_SHORTFALL}). "
                    "Download data/normalized/search_index.json and rebuild with "
                    "python src/processing/r2_sync.py rebuild-home-feeds"
                )


def _validate_normalized_upload(
    paths: Sequence[Tuple[Path, str]],
) -> List[Tuple[Path, str]]:
    """Skip critical normalized keys when meta/bills/search_index counts diverge hard."""
    by_key = {key: path for path, key in paths}
    uploading_critical = [key for key in CRITICAL_NORMALIZED_KEYS if key in by_key]
    if not uploading_critical:
        return list(paths)

    counts = _collect_normalized_bill_counts(paths)
    # Only compare among files that exist; require at least two signals.
    if len(counts) < 2:
        for key, n in sorted(counts.items()):
            print(f"{key} bill count OK ({n})")
        return list(paths)

    issues = _normalized_consistency_issues(counts)
    summary = ", ".join(f"{Path(k).name}={n}" for k, n in sorted(counts.items()))
    if not issues:
        print(f"normalized bill counts OK ({summary})")
        return list(paths)

    detail = "; ".join(issues)
    print(
        f"WARNING: refusing upload of critical normalized keys due to count mismatch "
        f"({summary}). Divergences: {detail}"
    )
    raise SystemExit(
        "Refusing to upload truncated/inconsistent normalized data: "
        f"{detail}. "
        f"Need meta.counts.bills ≈ len(bills) ≈ len(search_index.bills) "
        f"(within {NORMALIZED_COUNT_MAX_REL_GAP:.0%} or "
        f"{NORMALIZED_COUNT_MAX_ABS_GAP} bills). "
        "Re-run normalize_data before publishing."
    )


def upload(paths: Sequence[Tuple[Path, str]], *, dry_run: bool = False) -> int:
    bucket = os.environ.get("R2_BUCKET_NAME", "").strip() or "PolicyWatch-data"
    if not dry_run:
        bucket = _require_env("R2_BUCKET_NAME")
    _validate_docs_upload(paths)
    paths = _validate_normalized_upload(paths)
    if dry_run:
        for path, key in paths:
            print(f"DRY-RUN upload {path} -> s3://{bucket}/{key} ({path.stat().st_size} bytes)")
        return len(paths)

    client = _client()
    uploaded = 0
    for path, key in paths:
        size = path.stat().st_size
        print(f"upload {key} ({size / (1024 * 1024):.1f} MB)")
        extra = {
            "ContentType": _content_type(path),
            "CacheControl": "public, max-age=60",
        }
        client.upload_file(str(path), bucket, key, ExtraArgs=extra)
        uploaded += 1
    print(f"Uploaded {uploaded} objects to r2://{bucket}")
    return uploaded


def write_data_config() -> Path:
    """Write docs/data-config.js so the site knows where to fetch JSON."""
    base = (os.environ.get("R2_PUBLIC_BASE_URL") or "").strip().rstrip("/")
    out = ROOT / "docs" / "data-config.js"
    contents = (
        "/* Generated by CI — PolicyWatch data base URL (Cloudflare R2). */\n"
        f"window.POLICYWATCH_DATA_BASE = {base!r};\n"
        "window.CIVICWATCH_DATA_BASE = window.POLICYWATCH_DATA_BASE;\n"
    )
    out.write_text(contents, encoding="utf-8")
    print(f"Wrote {out} with base={base or '(empty — same-origin)'}")
    return out


def _local_path_for_r2_key(key: str) -> Path:
    """Map an R2 object key to a workspace path."""
    rel = key.replace("\\", "/").lstrip("/")
    if rel.startswith("docs/") or rel.startswith("data/"):
        return ROOT / rel
    # Browser-facing docs objects are stored with keys relative to docs/.
    return ROOT / "docs" / rel


def download_keys(keys: Sequence[str], *, dry_run: bool = False) -> int:
    """Download specific object keys from R2 into the workspace."""
    bucket = _require_env("R2_BUCKET_NAME")
    if dry_run:
        for key in keys:
            print(f"DRY-RUN download s3://{bucket}/{key} -> {_local_path_for_r2_key(key)}")
        return len(list(keys))

    client = _client()
    downloaded = 0
    for key in keys:
        dest = _local_path_for_r2_key(key)
        dest.parent.mkdir(parents=True, exist_ok=True)
        print(f"download {key} -> {dest}")
        client.download_file(bucket, key, str(dest))
        downloaded += 1
    print(f"Downloaded {downloaded} objects from R2")
    return downloaded


def rebuild_home_feeds_from_site_data(*, site_data_path: Path | None = None) -> int:
    """Rebuild slim home_feed.json + per-day files from docs/site_data.json.

    Homepage archive search must cover the full normalized corpus. site_data.json
    often ships a stale/partial search_index, so prefer data/normalized/search_index.json
    when it contains more bills.
    """
    from processing.home_feed import write_home_feed_artifacts

    from processing.legislators_directory import load_enabled_states

    path = site_data_path or (ROOT / "docs" / "site_data.json")
    if not path.is_file():
        raise SystemExit(f"Missing site data for home feed rebuild: {path}")
    site = json.loads(path.read_text(encoding="utf-8"))
    veteran = site.get("veteran_impact") or {}
    search_index = prefer_search_index(site.get("search_index") or {})
    states = load_enabled_states() or list(site.get("states") or [])
    home_path, day_paths, payload = write_home_feed_artifacts(
        ROOT / "docs",
        last_updated=site.get("last_updated") or "",
        site_years=site.get("years") or {},
        search_index=search_index,
        states=states,
        veteran_impact_lookup=(veteran.get("lookup") or {}),
        kansas_vote_records=site.get("kansas_vote_records") or {},
        action_badges=site.get("action_badges") or {},
    )
    stats = payload.get("stats") or {}
    print(
        f"Rebuilt {home_path} and {len(day_paths)} day files "
        f"({stats.get('available_day_count', 0)} available days; "
        f"{stats.get('home_search_bill_count', 0)} search bills)"
    )
    return len(day_paths)


def rebuild_legislators_directory_from_site_data(
    *, site_data_path: Path | None = None
) -> Path:
    """Rebuild docs/legislators_directory.json from normalized + site_data sources."""
    from processing.legislators_directory import (
        load_enabled_states,
        write_legislators_directory_artifacts,
    )

    path = site_data_path or (ROOT / "docs" / "site_data.json")
    if not path.is_file():
        raise SystemExit(f"Missing site data for legislators directory rebuild: {path}")
    site = json.loads(path.read_text(encoding="utf-8"))
    search_index = prefer_search_index(site.get("search_index") or {})
    legislators = prefer_legislators(
        site.get("search_index") or {},
        preferred_index=search_index,
    )
    legislator_stats = prefer_legislator_stats(site.get("legislator_stats") or {})
    # Never trust stale site_data.states alone — states.yaml is the source of truth.
    states = load_enabled_states() or list(site.get("states") or [])
    out_path, payload = write_legislators_directory_artifacts(
        ROOT / "docs",
        legislators=legislators,
        legislator_stats=legislator_stats,
        states=states,
        generated_at=site.get("last_updated") or "",
    )
    stats = payload.get("stats") or {}
    state_codes = [s.get("code") for s in (payload.get("states") or [])]
    print(
        f"Rebuilt {out_path} "
        f"({stats.get('legislator_count', 0)} legislators, "
        f"{len(state_codes)} states {state_codes}, "
        f"{out_path.stat().st_size / 1024:.1f} KB)"
    )
    return out_path


def rebuild_vote_and_bill_docs_from_sources() -> Dict[str, Any]:
    """Rebuild legislator vote + bill lookup docs from openstates/normalized data.

    Never uses site_data.json — normalized votes.json is often slimmed, so roll
    calls are loaded from data/openstates/*/votes.json for enabled states.
    """
    from processing.vote_docs import rebuild_vote_and_bill_docs

    stats = rebuild_vote_and_bill_docs(write_normalized=True)
    vote_states = (stats.get("votes") or {}).get("by_state") or {}
    if len(vote_states) < 8:
        raise SystemExit(
            f"Vote docs rebuild produced too few states ({vote_states}). "
            "Download data/openstates/*/votes.json for enabled states and retry."
        )
    return stats


def rebuild_hearings_feed_from_site_data(
    *, site_data_path: Path | None = None
) -> Path:
    """Rebuild docs/hearings.json from site_data + normalized events + states.yaml."""
    from processing.hearings_feed import (
        prefer_hearings_from_normalized,
        write_hearings_feed_artifacts,
    )
    from processing.legislators_directory import load_enabled_states

    path = site_data_path or (ROOT / "docs" / "site_data.json")
    if not path.is_file():
        raise SystemExit(f"Missing site data for hearings feed rebuild: {path}")
    site = json.loads(path.read_text(encoding="utf-8"))
    upcoming, historical = prefer_hearings_from_normalized(
        site.get("upcoming_hearings") or [],
        site.get("historical_hearings") or [],
    )
    # Never trust stale site_data.states alone — states.yaml is the source of truth.
    states = load_enabled_states() or list(site.get("states") or [])
    out_path, payload = write_hearings_feed_artifacts(
        ROOT / "docs",
        upcoming_hearings=upcoming,
        historical_hearings=historical,
        kansas_calendars=site.get("kansas_calendars") or {},
        states=states,
        generated_at=site.get("last_updated") or "",
    )
    stats = payload.get("stats") or {}
    state_codes = [s.get("code") for s in (payload.get("states") or [])]
    print(
        f"Rebuilt {out_path} "
        f"({stats.get('upcoming_count', 0)} upcoming, "
        f"{stats.get('historical_count', 0)} historical, "
        f"{len(state_codes)} states {state_codes}, "
        f"{out_path.stat().st_size / 1024:.1f} KB)"
    )
    return out_path


def download_pipeline(*, dry_run: bool = False) -> int:
    """Restore pipeline caches from R2 into the workspace (best-effort)."""
    bucket = _require_env("R2_BUCKET_NAME")
    prefixes = ["data/normalized/", "data/openstates/"]
    if dry_run:
        print(f"DRY-RUN download prefixes {prefixes} from {bucket}")
        return 0

    client = _client()
    downloaded = 0
    for prefix in prefixes:
        token = None
        while True:
            kwargs = {"Bucket": bucket, "Prefix": prefix}
            if token:
                kwargs["ContinuationToken"] = token
            resp = client.list_objects_v2(**kwargs)
            for obj in resp.get("Contents") or []:
                key = obj["Key"]
                dest = ROOT / key
                dest.parent.mkdir(parents=True, exist_ok=True)
                print(f"download {key} -> {dest}")
                client.download_file(bucket, key, str(dest))
                downloaded += 1
            if not resp.get("IsTruncated"):
                break
            token = resp.get("NextContinuationToken")
    print(f"Downloaded {downloaded} pipeline objects from R2")
    return downloaded


def main(argv: Iterable[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    up = sub.add_parser("upload", help="Upload docs + pipeline JSON to R2")
    up.add_argument("--docs-only", action="store_true")
    up.add_argument("--pipeline-only", action="store_true")
    up.add_argument("--dry-run", action="store_true")

    sub.add_parser("write-config", help="Write docs/data-config.js from R2_PUBLIC_BASE_URL")

    down = sub.add_parser("download-pipeline", help="Download pipeline caches from R2")
    down.add_argument("--dry-run", action="store_true")

    dl = sub.add_parser("download", help="Download specific R2 object keys")
    dl.add_argument("keys", nargs="+", help="R2 keys (e.g. site_data.json)")
    dl.add_argument("--dry-run", action="store_true")

    sub.add_parser(
        "rebuild-home-feeds",
        help="Rebuild home_feed.json + home_feed_days/ from docs/site_data.json",
    )
    sub.add_parser(
        "rebuild-legislators-directory",
        help="Rebuild legislators_directory.json from normalized + site_data",
    )
    sub.add_parser(
        "rebuild-hearings-feed",
        help="Rebuild hearings.json from site_data + normalized events",
    )
    sub.add_parser(
        "rebuild-vote-docs",
        help=(
            "Rebuild legislator_votes/vote_counts + bill_*_lookup from "
            "openstates votes and normalized/openstates bills"
        ),
    )

    args = parser.parse_args(list(argv) if argv is not None else None)

    if args.command == "write-config":
        write_data_config()
        return

    if args.command == "download-pipeline":
        download_pipeline(dry_run=args.dry_run)
        return

    if args.command == "download":
        download_keys(args.keys, dry_run=args.dry_run)
        return

    if args.command == "rebuild-home-feeds":
        rebuild_home_feeds_from_site_data()
        return

    if args.command == "rebuild-legislators-directory":
        rebuild_legislators_directory_from_site_data()
        return

    if args.command == "rebuild-hearings-feed":
        rebuild_hearings_feed_from_site_data()
        return

    if args.command == "rebuild-vote-docs":
        rebuild_vote_and_bill_docs_from_sources()
        return

    if args.command == "upload":
        pairs: List[Tuple[Path, str]] = []
        if args.pipeline_only:
            pairs.extend(_collect_pipeline_files())
        elif args.docs_only:
            pairs.extend(_collect_docs_files())
        else:
            pairs.extend(_collect_docs_files())
            pairs.extend(_collect_pipeline_files())
        # de-dupe by key
        seen = set()
        unique = []
        for path, key in pairs:
            if key in seen:
                continue
            seen.add(key)
            unique.append((path, key))
        write_data_config()
        upload(unique, dry_run=args.dry_run)
        return

    raise SystemExit(f"Unknown command: {args.command}")


if __name__ == "__main__":
    main()
